/*
 * JS for Facebook_Login generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'da764cdb-3229-46d7-9f98-087c70a41728';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Facebook_Login",
    "location": "Facebook_Login.html"
}, {
    "name": "get_help",
    "location": "get_help.html"
}, {
    "name": "Facebook_Me",
    "location": "Facebook_Me.html"
}, {
    "name": "track",
    "location": "track.html"
}, {
    "name": "Login",
    "location": "Login.html"
}, {
    "name": "forgotpassword",
    "location": "forgotpassword.html"
}, {
    "name": "details",
    "location": "details.html"
}, {
    "name": "profile",
    "location": "profile.html"
}, {
    "name": "calculate",
    "location": "calculate.html"
}];

function Facebook_Login_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton1': 'Facebook_Login_mobilebutton1'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'Facebook_Login';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Facebook_Login_onLoad = function() {
            Facebook_Login_elementsExtraJS();

            Facebook_Login_deviceEvents();
            Facebook_Login_windowEvents();
            Facebook_Login_elementsEvents();
        };

    // screen window events


    function Facebook_Login_windowEvents() {

        $('#Facebook_Login').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Facebook_Login_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Facebook_Login_elementsExtraJS() {
        // screen (Facebook_Login) extra code

    };

    // screen elements handler


    function Facebook_Login_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Facebook_Login_mobilecontainer1 [name="mobilebutton1"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Helper.init();;

                }
            },
        }, '#Facebook_Login_mobilecontainer1 [name="mobilebutton1"]');

    };

    $(document).off("pagebeforeshow", "#Facebook_Login").on("pagebeforeshow", "#Facebook_Login", function(event, ui) {
        Apperyio.CurrentScreen = "Facebook_Login";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Facebook_Login_onLoad();
};

$(document).off("pagecreate", "#Facebook_Login").on("pagecreate", "#Facebook_Login", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Facebook_Login_js();
});