/*
 * JS for forgotpassword generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'da764cdb-3229-46d7-9f98-087c70a41728';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Facebook_Login",
    "location": "Facebook_Login.html"
}, {
    "name": "get_help",
    "location": "get_help.html"
}, {
    "name": "Facebook_Me",
    "location": "Facebook_Me.html"
}, {
    "name": "track",
    "location": "track.html"
}, {
    "name": "Login",
    "location": "Login.html"
}, {
    "name": "forgotpassword",
    "location": "forgotpassword.html"
}, {
    "name": "details",
    "location": "details.html"
}, {
    "name": "profile",
    "location": "profile.html"
}, {
    "name": "calculate",
    "location": "calculate.html"
}];

function forgotpassword_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'password1': 'forgotpassword_password1',
        'password2': 'forgotpassword_password2',
        'newpassword': 'forgotpassword_newpassword',
        'spacer_5': 'forgotpassword_spacer_5',
        'mobilelabel_6': 'forgotpassword_mobilelabel_6',
        'remove': 'forgotpassword_remove'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'forgotpassword';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var forgotpassword_onLoad = function() {
            forgotpassword_elementsExtraJS();

            forgotpassword_deviceEvents();
            forgotpassword_windowEvents();
            forgotpassword_elementsEvents();
        };

    // screen window events


    function forgotpassword_windowEvents() {

        $('#forgotpassword').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function forgotpassword_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function forgotpassword_elementsExtraJS() {
        // screen (forgotpassword) extra code

    };

    // screen elements handler


    function forgotpassword_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#forgotpassword_mobilecontainer [name="newpassword"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var password1;
                    var password2;

                    password1 = Apperyio('password1').val();
                    password2 = Apperyio('password2').val();

                    if (password1 == password2) {
                        Apperyio.storage.password1.set(password1);
                        alert("New password has been set.");
                    } else {
                        alert("Sorry, passwords do not match.");
                    };
                    Apperyio.navigateTo('Login', {
                        reverse: false
                    });

                }
            },
        }, '#forgotpassword_mobilecontainer [name="newpassword"]');

        $(document).off("click", '#forgotpassword_mobilecontainer [name="remove"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.storage.password1.set(null);
                    alert("Password has been removed");
                    Apperyio.navigateTo('calculate', {
                        reverse: false
                    });

                }
            },
        }, '#forgotpassword_mobilecontainer [name="remove"]');

    };

    $(document).off("pagebeforeshow", "#forgotpassword").on("pagebeforeshow", "#forgotpassword", function(event, ui) {
        Apperyio.CurrentScreen = "forgotpassword";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    forgotpassword_onLoad();
};

$(document).off("pagecreate", "#forgotpassword").on("pagecreate", "#forgotpassword", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    forgotpassword_js();
});