/*
 * JS for profile generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'da764cdb-3229-46d7-9f98-087c70a41728';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Facebook_Login",
    "location": "Facebook_Login.html"
}, {
    "name": "get_help",
    "location": "get_help.html"
}, {
    "name": "Facebook_Me",
    "location": "Facebook_Me.html"
}, {
    "name": "track",
    "location": "track.html"
}, {
    "name": "Login",
    "location": "Login.html"
}, {
    "name": "forgotpassword",
    "location": "forgotpassword.html"
}, {
    "name": "details",
    "location": "details.html"
}, {
    "name": "profile",
    "location": "profile.html"
}, {
    "name": "calculate",
    "location": "calculate.html"
}];

function profile_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'prof': 'profile_prof',
        'mobilelabel_26': 'profile_mobilelabel_26',
        'profile_picture': 'profile_profile_picture',
        'takephotobutton': 'profile_takephotobutton',
        'usepicture': 'profile_usepicture',
        'spacer_28': 'profile_spacer_28',
        'mobilelabel_34': 'profile_mobilelabel_34',
        'targetmessage': 'profile_targetmessage',
        'mobilegrid_35': 'profile_mobilegrid_35',
        'mobilegridcell_36': 'profile_mobilegridcell_36',
        'mobilelabel_40': 'profile_mobilelabel_40',
        'mobilegridcell_37': 'profile_mobilegridcell_37',
        'profilefirstname': 'profile_profilefirstname',
        'mobilegridcell_38': 'profile_mobilegridcell_38',
        'mobilelabel_60': 'profile_mobilelabel_60',
        'mobilegridcell_39': 'profile_mobilegridcell_39',
        'profilelastname': 'profile_profilelastname',
        'mobilegridcell_42': 'profile_mobilegridcell_42',
        'mobilelabel_41': 'profile_mobilelabel_41',
        'mobilegridcell_43': 'profile_mobilegridcell_43',
        'profileage': 'profile_profileage',
        'mobilegridcell_44': 'profile_mobilegridcell_44',
        'mobilelabel_46': 'profile_mobilelabel_46',
        'mobilegridcell_45': 'profile_mobilegridcell_45',
        'amountstart': 'profile_amountstart',
        'mobilegridcell_48': 'profile_mobilegridcell_48',
        'mobilelabel_47': 'profile_mobilelabel_47',
        'mobilegridcell_49': 'profile_mobilegridcell_49',
        'amountnow': 'profile_amountnow',
        'mobilegridcell_58': 'profile_mobilegridcell_58',
        'mobilelabel_50': 'profile_mobilelabel_50',
        'mobilegridcell_59': 'profile_mobilegridcell_59',
        'amounttarget': 'profile_amounttarget',
        'mobilebutton_57': 'profile_mobilebutton_57',
        'navbar1': 'profile_navbar1',
        'mobilenavbaritem_3': 'profile_mobilenavbaritem_3',
        'mobilenavbaritem_4': 'profile_mobilenavbaritem_4',
        'mobilenavbaritem_5': 'profile_mobilenavbaritem_5',
        'mobilenavbaritem_6': 'profile_mobilenavbaritem_6'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["profile_camera_shot_onsuccess_mapping_0"] = {
        "homeScreen": "profile",
        "directions": [

        {
            "from_name": "camera_shot",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "profile",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['data']['imageDataBase64']",
                "target": "$['profile_picture:image']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["profile_camera_shot_onbeforesend_mapping_0"] = {
        "homeScreen": "profile",
        "directions": [

        {

            "to_name": "camera_shot",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "data": {
                    "quality": 80,
                    "destinationType": "Data URL",
                    "sourceType": "Camera",
                    "allowEdit": true,
                    "encodingType": "JPEG",
                    "targetWidth": 1024,
                    "targetHeight": 768
                }
            },

            "mappings": []
        }

        ]
    };

    Apperyio.mappings["profile_profiledata_onsuccess_mapping_0"] = {
        "homeScreen": "profile",
        "directions": [

        {
            "from_name": "profiledata",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "profile",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body'][0]['age']",
                "target": "$['profileage:text']"

            },

            {

                "source": "$['body'][0]['firstname']",
                "target": "$['profilefirstname:text']"

            },

            {

                "source": "$['body'][0]['lastname']",
                "target": "$['profilelastname:text']"

            },

            {

                "source": "$['body'][0]['startamount']",
                "target": "$['amountstart:text']"

            },

            {

                "source": "$['body'][0]['currentamount']",
                "target": "$['amountnow:text']"

            },

            {

                "source": "$['body'][0]['targetamount']",
                "target": "$['amounttarget:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["profile_profiledata_onbeforesend_mapping_0"] = {
        "homeScreen": "profile",
        "directions": [

        {

            "to_name": "profiledata",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "X-Appery-Database-Id": "{database_id}"
                },
                "parameters": {},
                "body": null
            },

            "mappings": []
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.camera_shot = Apperyio.datasources.camera_shot = new Apperyio.DataSource(CameraService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["profile_camera_shot_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["profile_camera_shot_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.profiledata = Apperyio.datasources.profiledata = new Apperyio.DataSource(smoketrack_db_profile_list_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["profile_profiledata_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["profile_profiledata_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'profile';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var profile_onLoad = function() {
            profile_elementsExtraJS();

            //Center the image and button
            Apperyio('prof').css('margin', 'auto');
            Apperyio('prof').css('display', 'block');

            Apperyio('profile_picture').css('margin', 'auto');
            Apperyio('profile_picture').css('display', 'block');
            try {
                $a.c15r("profilefirstname", "set", "text", $a.storage["profile_firstname"].get("$"))
            } catch (e) {
                console.error(e)
            };
            try {
                $a.c15r("profilelastname", "set", "text", $a.storage["profile_lastname"].get("$"))
            } catch (e) {
                console.error(e)
            };
            try {
                $a.c15r("profileage", "set", "text", $a.storage["profile_age"].get("$"))
            } catch (e) {
                console.error(e)
            };
            try {
                $a.c15r("amountstart", "set", "text", $a.storage["profile_startamount"].get("$"))
            } catch (e) {
                console.error(e)
            };
            try {
                $a.c15r("amountnow", "set", "text", $a.storage["profile_currentamount"].get("$"))
            } catch (e) {
                console.error(e)
            };
            try {
                $a.c15r("amounttarget", "set", "text", $a.storage["profile_targetamount"].get("$"))
            } catch (e) {
                console.error(e)
            };
            setAttribute_('profile_profile_picture', 'src', $a.storage["profile_image"].get("$"));
            $('[id="profile_profile_picture"]').refresh();
/*
	- Display a message to output the user's progress
    - Display amount difference from start
    - Display amount until target reached
*/

            //Declare variables
            var amountNow, amountTarget;

            //Set variables 
            amountNow = Apperyio.storage.profile_currentamount.get();
            amountTarget = Apperyio.storage.profile_targetamount.get();
            //alert(amountNow +"\n"+ amountTarget);

            //Display a  different message if the user has set their current amount to 0 (quit smoking)
            if (amountNow < 1) {
                Apperyio('targetmessage').text("Congratulations, you have managed to completely quit smoking!");
            }
            //Display message if user has reached target
            else if (amountTarget >= amountNow) {
                Apperyio('targetmessage').text("Congratulations, you have successfully reached your newest target of smoking " + amountTarget + " cigarettes per day!");
            }

            //Display a message if the user has not reached their target
            else {
                var amountUntil;
                amountUntil = amountNow - amountTarget;
                Apperyio('targetmessage').text("Keep going! You need to cut down by " + amountUntil + " more per day until you've reached your newest target!");
            };

            profile_deviceEvents();
            profile_windowEvents();
            profile_elementsEvents();
        };

    // screen window events


    function profile_windowEvents() {

        $('#profile').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#profile').on({
            swiperight: function(event) {
                Apperyio.navigateTo('get_help', {
                    transition: 'pop',
                    reverse: false
                });
            },
        });

    };

    // device events


    function profile_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function profile_elementsExtraJS() {
        // screen (profile) extra code

    };

    // screen elements handler


    function profile_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#profile_mobilecontainer [name="takephotobutton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        camera_shot.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                    try {
                        $a.storage["profile_image"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('profile_picture', this), 'get', 'image'))
                    } catch (e) {
                        console.error(e)
                    };

                }
            },
        }, '#profile_mobilecontainer [name="takephotobutton"]');
        $(document).off("click", '#profile_mobilecontainer [name="usepicture"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["profile_image"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('profile_picture', this), 'get', 'image'))
                    } catch (e) {
                        console.error(e)
                    };
                    alert("Profile picture has been saved");

                }
            },
        }, '#profile_mobilecontainer [name="usepicture"]');

        $(document).off("click", '#profile_mobilecontainer [name="mobilebutton_57"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('details', {
                        reverse: false
                    });

                }
            },
        }, '#profile_mobilecontainer [name="mobilebutton_57"]');

        $(document).off("click", '#profile_mobilefooter [name="mobilenavbaritem_3"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('calculate', {
                        reverse: false
                    });

                }
            },
        }, '#profile_mobilefooter [name="mobilenavbaritem_3"]');
        $(document).off("click", '#profile_mobilefooter [name="mobilenavbaritem_4"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('track', {
                        reverse: false
                    });

                }
            },
        }, '#profile_mobilefooter [name="mobilenavbaritem_4"]');
        $(document).off("click", '#profile_mobilefooter [name="mobilenavbaritem_5"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('get_help', {
                        reverse: false
                    });

                }
            },
        }, '#profile_mobilefooter [name="mobilenavbaritem_5"]');

    };

    $(document).off("pagebeforeshow", "#profile").on("pagebeforeshow", "#profile", function(event, ui) {
        Apperyio.CurrentScreen = "profile";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    profile_onLoad();
};

$(document).off("pagecreate", "#profile").on("pagecreate", "#profile", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    profile_js();
});