/*
 * JS for track generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'da764cdb-3229-46d7-9f98-087c70a41728';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Facebook_Login",
    "location": "Facebook_Login.html"
}, {
    "name": "get_help",
    "location": "get_help.html"
}, {
    "name": "Facebook_Me",
    "location": "Facebook_Me.html"
}, {
    "name": "track",
    "location": "track.html"
}, {
    "name": "Login",
    "location": "Login.html"
}, {
    "name": "forgotpassword",
    "location": "forgotpassword.html"
}, {
    "name": "details",
    "location": "details.html"
}, {
    "name": "profile",
    "location": "profile.html"
}, {
    "name": "calculate",
    "location": "calculate.html"
}];

function track_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'calendar': 'track_calendar',
        'mobilelabel_16': 'track_mobilelabel_16',
        'mobilelabel_8': 'track_mobilelabel_8',
        'spacer_10': 'track_spacer_10',
        'mobilelabel_39': 'track_mobilelabel_39',
        'facebookpic': 'track_facebookpic',
        'loginfacebook': 'track_loginfacebook',
        'spacer_38': 'track_spacer_38',
        'mobilelabel_9': 'track_mobilelabel_9',
        'amount': 'track_amount',
        'saveamount': 'track_saveamount',
        'spacer_15': 'track_spacer_15',
        'mobilelabel_13': 'track_mobilelabel_13',
        'mobilegrid_17': 'track_mobilegrid_17',
        'mobilegridcell_18': 'track_mobilegridcell_18',
        'mobilelabel_28': 'track_mobilelabel_28',
        'mobilegridcell_19': 'track_mobilegridcell_19',
        'mobilelabel_33': 'track_mobilelabel_33',
        'mobilegridcell_20': 'track_mobilegridcell_20',
        'mobilelabel_29': 'track_mobilelabel_29',
        'mobilegridcell_21': 'track_mobilegridcell_21',
        'day1': 'track_day1',
        'mobilegridcell_22': 'track_mobilegridcell_22',
        'mobilelabel_30': 'track_mobilelabel_30',
        'mobilegridcell_23': 'track_mobilegridcell_23',
        'day7': 'track_day7',
        'mobilegridcell_24': 'track_mobilegridcell_24',
        'mobilelabel_31': 'track_mobilelabel_31',
        'mobilegridcell_25': 'track_mobilegridcell_25',
        'day14': 'track_day14',
        'mobilegridcell_26': 'track_mobilegridcell_26',
        'mobilelabel_32': 'track_mobilelabel_32',
        'mobilegridcell_27': 'track_mobilegridcell_27',
        'day28': 'track_day28',
        'navbar1': 'track_navbar1',
        'mobilenavbaritem_3': 'track_mobilenavbaritem_3',
        'mobilenavbaritem_4': 'track_mobilenavbaritem_4',
        'mobilenavbaritem_5': 'track_mobilenavbaritem_5',
        'mobilenavbaritem_6': 'track_mobilenavbaritem_6'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'track';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var track_onLoad = function() {
            track_elementsExtraJS();

            //Center the images
            Apperyio('facebookpic').css('margin', 'auto');
            Apperyio('facebookpic').css('display', 'block');

            Apperyio('calendar').css('margin', 'auto');
            Apperyio('calendar').css('display', 'block');

            track_deviceEvents();
            track_windowEvents();
            track_elementsEvents();
        };

    // screen window events


    function track_windowEvents() {

        $('#track').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#track').on({
            swiperight: function(event) {
                Apperyio.navigateTo('calculate', {
                    transition: 'pop',
                    reverse: false
                });
            },
            swipeleft: function(event) {
                Apperyio.navigateTo('get_help', {
                    transition: 'pop',
                    reverse: false
                });
            },
        });

    };

    // device events


    function track_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function track_elementsExtraJS() {
        // screen (track) extra code

    };

    // screen elements handler


    function track_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#track_mobilecontainer [name="loginfacebook"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Helper.init();

                }
            },
        }, '#track_mobilecontainer [name="loginfacebook"]');

        $(document).off("click", '#track_mobilecontainer [name="saveamount"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) { //Get the amount smoked today and set it to a variable
                    var amountToday = 0;
                    amountToday = Apperyio('amount').val();

                    Apperyio('day1').text(amountToday);

                }
            },
        }, '#track_mobilecontainer [name="saveamount"]');

        $(document).off("click", '#track_mobilefooter [name="mobilenavbaritem_3"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('calculate', {
                        reverse: false
                    });

                }
            },
        }, '#track_mobilefooter [name="mobilenavbaritem_3"]');

        $(document).off("click", '#track_mobilefooter [name="mobilenavbaritem_5"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('get_help', {
                        reverse: false
                    });

                }
            },
        }, '#track_mobilefooter [name="mobilenavbaritem_5"]');
        $(document).off("click", '#track_mobilefooter [name="mobilenavbaritem_6"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('profile', {
                        reverse: false
                    });

                }
            },
        }, '#track_mobilefooter [name="mobilenavbaritem_6"]');

    };

    $(document).off("pagebeforeshow", "#track").on("pagebeforeshow", "#track", function(event, ui) {
        Apperyio.CurrentScreen = "track";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    track_onLoad();
};

$(document).off("pagecreate", "#track").on("pagecreate", "#track", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    track_js();
});